### ISSUE TITLE
Critical Flaw:  Broken BIDMat Dense-Sparse Matrix Multiply

### ISSUE THREAD

**Issue by ago109** [BIDData/BIDMat#58] opened 2016-02-11 18:53 UTC
Hello,
I've been using the bleeding-edge/developer version of BIDMat (tried this with a clone of the version Feburary 2, and now a fresh pull today) and I have found that the dense-sparse matrix multiply no longer works.  At first I thought it had to do with my own library's (which is built on top of BIDMat) determinism (since it appears the results are different every re-run of the program), but then I ran this simple vignette after tracing the computation to its source problem:

```
    var datX = Array(1f, 0f, 1f, 0f, 0f, 0f,
                     0f, 1f, 1f, 0f, 0f, 0f,
                     1f, 1f, 1f, 0f, 0f, 0f,
                     0f, 0f, 0f, 1f, 0f, 1f,
                     0f, 0f, 0f, 0f, 1f, 1f,
                     0f, 0f, 0f, 1f, 1f, 1f)
    var x1 = new FMat(6,6,datX)
    var x2 = sparse(x1)
    println("prod:\n"+(x1 * x2)) 
```
Reproduced below are two subsequent runs of the program (in a Scala object with main method), labelled Trail 1 and Trial 2 respectively:

Trial 1:
_prod:
   1   0   4   0   0   0
   0   1   3   0   0   0
   1   1   5   0   0   0
   0   0   0   2   1   2
   0   0   0   1   2   2
  ..  ..  ..  ..  ..  .._

Trial 2:
_prod:
   1   1   2   0   0   1
   0   2   2   0   0   2
   1   2   3   0   0   2
   0   0   0   2   1   6
   0   0   0   1   2   5
  ..  ..  ..  ..  ..  .._

I'm not sure if as BIDMat has been updated something broke the matrix-matrix operations involving sparse matrices, at minimum the multiply.  Could you please look into this and fix this bug?  Your dense-sparse/sparse ops are quite critical and useful for my library's back-bone.  Note that this issue goes away when I do NOT use the most up-to-date version of BIDMat (but instead revert to one of the bundles available on the website).

Thanks!

**Comment by jcanny** [comment] 2016-02-11 20:52
Ach, We changed the native code recently to support ARM processors. there's a nasty interaction in the native code between OMP parallel for loops and cblas calls inside the loop. We knew this is a problem on ARM machines but we got it working and didnt think it would break Intel-Arch code, which uses MKL which is supposed to work with OMP. 

Anyway, I took out the CBLAS calls and just put in an explicit loop. Looks like the compiler is vectorizing that anyway, because the resulting code is actually about 2x faster. 

It should work from the main branch now. Since the changes were to the native code, you'll need to do getdevlibs.sh to get the updated libraries. I recompiled it for Windows and Linux. If you need Mac, I'll have to do that tonight when I have access to the Mac with the Intel compiler on it.

**Comment by ago109** [comment] 2016-02-12 03:54
Ok, well that solved the non-deterministic bug (I get the same results upon calling the same vignette multiple times), however, now when I run a program at a larger scale which requires many dense-sparse multiplies, I get a JVM failure:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5bec5f2dd8, pid=9266, tid=140033193834240
#
# JRE version: OpenJDK Runtime Environment (7.0_75-b13) (build 1.7.0_75-mockbuild_2015_01_20_23_39-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.75-b04 mixed mode linux-amd64 )
# Derivative: IcedTea 2.5.4
# Distribution: Built on CentOS release 6.6 (Final) (Tue Jan 20 23:39:59 UTC 2015)
# Problematic frame:
# C  [libbidmatcpu-linux-x86_64.so+0x153dd8]  Java_edu_berkeley_bid_SPBLAS_smcscm+0x6a8
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/jvm-9266/hs_error.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
```
And upon glancing at the error log/core dump in /tmp/ for the crashed JVM, I traced the issue it looks like to native code with respect to:

```
Stack: [0x00007f5c04867000,0x00007f5c04c68000],  sp=0x00007f5c04c66650,  free space=4093k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libbidmatcpu-linux-x86_64.so+0x153dd8]  Java_edu_berkeley_bid_SPBLAS_smcscm+0x6a8

[error occurred during error reporting (printing native stack), id 0xb]
```
Not sure what's going on, but something is breaking it seems at the native level regarding "libbidmatcpu-linux-x86_64.so"?

**Comment by jcanny** [comment] 2016-02-14 23:31
Hi, give us a complete bug report, and we should be able to fix it. Any bug report should have at a minumum:
* the system you ran on, hardware and OS
* key dependencies, which are here the JVM version and CUDA version. 
* the problem, in enough detail for us to reproduce it. 

It looks like you ran an openJDK VM on centOS? We officially support Oracle, and the libs are built with Oracle's SDK. This often works on OpenJDK, but its asking for trouble. 

Please also check your sparse matrix integrity with "s.check" where s is your sparse matrix. We dont check the integrity of sparse matrices during calculations for performance reasons, and they can easily cause memory errors if the indices are out of range.

**Comment by jcanny** [comment] 2016-02-15 01:02
Never mind, it was an obvious problem. Fixed in the master branch for source and for windows and linux binaries. 

We do appreciate more detailed bug reports however. It usually narrows down the possible causes a lot.

**Comment by ago109** [comment] 2016-02-15 16:17
I was just about to prepare a few more details to specify what I was doing, but did you figure out the issue already?  Should I pull the newest git version and try again to see if I get the same issue?

**Comment by jcanny** [comment] 2016-02-16 03:39
Yes, it should be fixed. Binaries uploaded for WIndows, Mac and Linux now. Youll need to do getdevlibs.sh to get them.

**Closed** 2016-05-14 00:22 UTC
